name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Install PowerShell
        shell: bash
        run: |
          pwsh --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fritzconnection

      - name: Run tests
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
          $config = New-PesterConfiguration
          $config.Run.Path = './NetWatch.Tests.ps1'
          $config.Run.Exit = $true
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config

      - name: Validate Python scripts
        run: |
          python -m py_compile fritzlog_pull.py
          python -m py_compile analyze_netlogs.py
          python -c "import fritzlog_pull"
          python -c "import analyze_netlogs"

      - name: Create release package
        run: |
          mkdir -p release
          cp NetWatch.ps1 release/
          cp fritzlog_pull.py release/
          cp analyze_netlogs.py release/
          cp README.md release/
          
          # Create a requirements.txt for Python dependencies
          echo "fritzconnection>=1.15.0" > release/requirements.txt
          
          # Create installation guide
          cat > release/INSTALL.md << 'EOF'
          # Installation Guide
          
          ## Prerequisites
          
          ### For NetWatch.ps1 (Windows only)
          - Windows PowerShell 5+ or PowerShell Core 7+
          - Administrator privileges recommended
          
          ### For Python Scripts
          - Python 3.10 or higher
          
          ## Installation Steps
          
          1. Extract all files to a directory of your choice
          
          2. Install Python dependencies:
             ```bash
             pip install -r requirements.txt
             ```
          
          3. Run the scripts as needed:
             - Windows: `.\NetWatch.ps1`
             - Linux/Mac: `python3 fritzlog_pull.py --password YOUR_PASSWORD`
             - Analysis: `python3 analyze_netlogs.py --netwatch LOG1.csv --fritz LOG2.csv`
          
          For detailed usage instructions, see README.md
          EOF

      - name: Create ZIP archive
        run: |
          cd release
          zip -r ../ping-${{ steps.version.outputs.version }}.zip .
          cd ..

      - name: Create tarball
        run: |
          cd release
          tar -czf ../ping-${{ steps.version.outputs.version }}.tar.gz .
          cd ..

      - name: Generate checksums
        run: |
          sha256sum ping-${{ steps.version.outputs.version }}.zip > checksums.txt
          sha256sum ping-${{ steps.version.outputs.version }}.tar.gz >> checksums.txt

      - name: Generate release notes
        id: release_notes
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          cat > release_notes.md << 'EOF'
          ## Network Monitoring Tools Release
          
          This release includes the complete network monitoring toolkit:
          
          ### Components
          - **NetWatch.ps1** - Windows PowerShell network monitoring script
          - **fritzlog_pull.py** - FRITZ!Box router status logger
          - **analyze_netlogs.py** - Log analysis and incident detection tool
          
          ### Installation
          
          Download either the `.zip` or `.tar.gz` archive and extract it. See `INSTALL.md` for detailed installation instructions.
          
          ### Requirements
          
          **For NetWatch.ps1:**
          - Windows PowerShell 5+ or PowerShell Core 7+
          - Windows OS (uses Windows-specific cmdlets)
          
          **For Python scripts:**
          - Python 3.10 or higher
          - Dependencies: `fritzconnection` (install via `pip install -r requirements.txt`)
          
          ### Quick Start
          
          ```bash
          # Install Python dependencies
          pip install -r requirements.txt
          
          # Run network monitor (Windows)
          .\NetWatch.ps1
          
          # Run FRITZ!Box logger
          python3 fritzlog_pull.py --password YOUR_PASSWORD
          
          # Analyze logs
          python3 analyze_netlogs.py --netwatch netwatch_log.csv --fritz fritz_log.csv
          ```
          
          ### Checksums
          
          Verify your download using SHA256:
          
          ```
          EOF
          
          cat checksums.txt >> release_notes.md
          
          echo '```' >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            ping-${{ steps.version.outputs.version }}.zip
            ping-${{ steps.version.outputs.version }}.tar.gz
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ steps.version.outputs.version }}
          path: |
            ping-${{ steps.version.outputs.version }}.zip
            ping-${{ steps.version.outputs.version }}.tar.gz
            checksums.txt
            release_notes.md
