name: Windows Testing

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 12 * * *'  # Run daily at noon UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-powershell-windows:
    name: Test PowerShell on Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -SkipPublisherCheck
          Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck

      - name: Validate syntax
        shell: pwsh
        run: |
          $ast = [System.Management.Automation.Language.Parser]::ParseFile("./NetWatch.ps1", [ref]$null, [ref]$null)
          if ($ast) {
            Write-Host "✓ Syntax validation passed on Windows"
          } else {
            Write-Error "Syntax validation failed"
            exit 1
          }

      - name: Run Pester tests
        shell: pwsh
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = './NetWatch.Tests.ps1'
          $config.Run.Exit = $true
          $config.Output.Verbosity = 'Detailed'
          Invoke-Pester -Configuration $config

  test-python-windows:
    name: Test Python 3.12 on Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fritzconnection

      - name: Test fritzlog_pull.py
        run: |
          python -m py_compile fritzlog_pull.py
          python -c "import fritzlog_pull; print('✓ Import successful')"
          python fritzlog_pull.py --help

      - name: Test analyze_netlogs.py
        run: |
          python -m py_compile analyze_netlogs.py
          python -c "import analyze_netlogs; print('✓ Import successful')"
          python analyze_netlogs.py --help

  integration-test:
    name: Integration Test
    runs-on: windows-latest
    needs: [test-powershell-windows, test-python-windows]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install fritzconnection

      - name: Install PowerShell modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck

      - name: Run all validations
        run: |
          echo "Testing Python scripts..."
          python -m py_compile fritzlog_pull.py
          python -m py_compile analyze_netlogs.py
          python fritzlog_pull.py --help
          python analyze_netlogs.py --help
          echo "✓ Python validations passed"

      - name: Run PowerShell tests
        shell: pwsh
        run: |
          Write-Host "Testing PowerShell script..."
          $config = New-PesterConfiguration
          $config.Run.Path = './NetWatch.Tests.ps1'
          $config.Run.Exit = $true
          $config.Output.Verbosity = 'Normal'
          Invoke-Pester -Configuration $config
          Write-Host "✓ PowerShell tests passed"

      - name: Summary
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "### ✅ Integration Tests Passed"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value ""
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "All scripts validated successfully on Windows:"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Python 3.12"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- PowerShell syntax and tests"
